# Header
menu:
  主页: /
  所有文章: /archives
  阅读计划: /categories/book

# SubNav
subnav:
  github: "https://github.com/seamys"
  weibo: "http://weibo.com/u/1661084192"
  #rss: "#"
  zhihu: "https://www.zhihu.com/people/ku-mi-tian-frllk"
  #douban: "#"
  mail: "yiim@foxmail.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: false
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
analytics: '52422'
favicon: /favicon.ico

#你的头像url
avatar: "https://avatars2.githubusercontent.com/u/7090368?v=3&s=460"
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: frllk
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: false
#开启——
#friends:

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
#aboutme: 我是谁，我从哪里来，我到哪里去？我就是我，是颜色不一样的吃货…
